server:
  port: "3001"
  gin_mode: "debug"
  domain: "localhost:3001/"

database:
  driver: "postgres"
  dsn: "host=localhost user=zhangziheng  dbname=shorturl port=5432 sslmode=disable TimeZone=Asia/Shanghai"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0